(
 ("ii" . ((user-emacs-directory . "~/humacs/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/humacs/ii-config")))))
 ("wilinux" . ((user-emacs-directory . "~/humacs/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/humacs/wilinux-config")))))
 ("doom" . ((user-emacs-directory . "~/humacs/doom-emacs")
           (env . (("DOOMDIR" . "~/humacs/doom-config")))))
 ("sachac" . ((user-emacs-directory . "~/humacs/sachac")))
 ("prelude" . ((user-emacs-directory . "~/humacs/prelude")))
)
