(
 ("spacemacs" . ((user-emacs-directory . "~/humacs/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/humacs/spacemacs-config")))))
 ("wil-spacemacs" . ((user-emacs-directory . "~/humacs/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/humacs/wil-spacemacs-config")))))
 ("doom" . ((user-emacs-directory . "~/humacs/doom-emacs")
           (env . (("DOOMDIR" . "~/humacs/doom-config")))))
 ("sachac" . ((user-emacs-directory . "~/humacs/sachac")))
 ("prelude" . ((user-emacs-directory . "~/humacs/prelude")))
)
