#+TITLE: Humacs

* Humacs

#+begin_quote
Macros for Humacs (aka Emacs for everyone)
#+end_quote

** Features

- Extensible IDE
- Runs everywhere
  - Locally (Linux, macOS, Windows)
  - Docker
  - Kubernetes
- Mnemonic based flow
- Supports multiple configuration profiles in Emacs
- Integrates with tmate and tmux for pairing

** Philosophy

Vanilla Emacs is inaccessable to most humans, therefore the power of Org mode based documentation and workflows is unavailable.

Literate programming and DevOps when combined together make the documentation also executable - meaning for reproducable easily documented creations.

** Installation and deployment

To install or deploy, please checkout the [[./docs/DEPLOYMENT.org][deployment]] docs.

** Configuration

Humacs can be configured through environment variables, these are details in the [[./docs/CONFIGURATION.org][config docs]].

** Contributing

All contribution is welcome. For information, please check out the [[./docs/CONTRIBUTING.org][contributing docs]].

** License
Copyright 2020-2021 ii.
This project is licensed under the [BSD 2-clause](https://en.wikipedia.org/wiki/BSD_licenses#2-clause) and is [Open Source](https://en.wikipedia.org/wiki/Open_source).
This program comes with absolutely no warranty.
