apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: $svcName
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    io.sharing.pair/managed: "true"
    io.sharing.pair/port: "${portNumber}"
    io.sharing.pair/pid: "${pid}"
spec:
  rules:
    - host: ${hostName}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${svcName}
              servicePort: ${portNumberExpose}
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - ${hostName}
      secretName: letsencrypt-prod
