apiVersion: v1
kind: Service
metadata:
  name: $svcName
  labels:
    io.sharing.pair/managed: "true"
    io.sharing.pair/port: "${portNumber}"
    io.sharing.pair/pid: "${pid}"
spec:
  externalIPs:
    - ${SHARINGIO_PAIR_LOAD_BALANCER_IP}
  ports:
    - name: ${name}
      port: ${portNumberExpose}
      protocol: ${protocol}
      targetPort: ${portNumber}
  selector:
    app.kubernetes.io/name: humacs
  type: ClusterIP
