# -*- ii: humacs; -*-
#+TITLE: Deployment

Deploying Humacs in several environments.

For configuration, please refer to the [[./CONFIGURATION.org][configuration]] docs.

* Host system

Setting up on your host system can be done with the following three commands

#+begin_src shell
git clone --recursive https://github.com/humacs/humacs
export EMACSLOADPATH=$(pwd)/humacs:
emacs -nw
#+end_src

Setting up on your host system with doom profile just means adding env vars for doom.

#+begin_src shell
git clone --recursive https://github.com/humacs/humacs
export EMACSLOADPATH=$(pwd)/humacs:
export DOOMDIR=$(pwd)/humacs/doom-config
export HUMACS_PROFILE=doom
emacs -nw
#+end_src

* Notes
- the environment variable EMACSLOADPATH must be set on your system for the Humacs configuration to load correctly

* Kubernetes (Helm)

** Installation

Create namespace:
#+name: Create namespace
#+begin_src sh
  kubectl create namespace humacs
#+end_src

Install Humacs:
#+name: Install Humacs
#+begin_src sh
  helm install humacs --namespace humacs chart/humacs
#+end_src

Values are found in the [[./CONFIGURATION.org][configuration]] docs.

Once up and running, connect via kubectl:
#+begin_src shell
  kubectl -n humacs exec statefulset/humacs -- attach
#+end_src

* Docker

** Simple

Spin up a quick and default environment

#+begin_src shell
docker run -ti --rm registry.gitlab.com/humacs/humacs/ii:2020.09.09 emacs
#+end_src

** Configuring

The following command shows configuring:
- the Humacs profile to Doom; and
- mounting in the current directory into the /home/ii/workspace folder of the humacs container

#+begin_src shell
docker run -ti --rm \
  -e HUMACS_PROFILE=doom \
  -v $(pwd):/home/ii/workspace registry.gitlab.com/humacs/humacs/ii:2020.09.09 emacs /home/ii/workspace
#+end_src

** Simple-Init.sh

Simple init allows the environment to be set up with:
- tmate
- repos
- git name and email env

#+begin_src shell
  docker run -ti --rm \
    --user ii \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp:/tmp \
    -e HUMACS_DEBUG=true \
    -e GIT_AUTHOR_NAME="ii" \
    -e GIT_AUTHOR_EMAIL="myemail@example.com" \
    -e INIT_ORG_FILE="" \
    -e INIT_DEFAULT_DIR="/home/ii" \
    -e INIT_DEFAULT_REPOS="https://github.com/kubernetes/kubernetes https://github.com/cncf/apisnoop" \
    -e INIT_DEFAULT_REPOS_FOLDER="workspace" \
    registry.gitlab.com/humacs/humacs/ii:2020.09.09 simple-init.sh
#+end_src
